# Generated by Django 3.0.4 on 2020-03-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('country_code', models.CharField(max_length=50, unique=True)),
                ('country_prefix', models.CharField(max_length=50)),
                ('country_currency', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CountryModel',
            },
        ),
        migrations.CreateModel(
            name='IndustryCategoryModel',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_Code', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('category_created_on', models.DateTimeField(auto_now=True)),
                ('category_created_by', models.BigIntegerField()),
                ('category_modified_on', models.DateTimeField(auto_now_add=True)),
                ('category_modified_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'IndustryCategoryModel',
            },
        ),
        migrations.CreateModel(
            name='IndustryMaincoreModel',
            fields=[
                ('maincore_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maincore_name', models.CharField(max_length=50, unique=True)),
                ('maincore_Code', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('maincore_created_on', models.DateTimeField(auto_now=True)),
                ('maincore_created_by', models.BigIntegerField()),
                ('maincore_modified_on', models.DateTimeField(auto_now_add=True)),
                ('maincore_modified_by', models.BigIntegerField()),
            ],
            options={
                'db_table': 'IndustryMaincoreModel',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('state_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=50, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterApiApp.CountryModel')),
            ],
            options={
                'db_table': 'StateModel',
            },
        ),
        migrations.CreateModel(
            name='IndustrySubCategoryModel',
            fields=[
                ('sub_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=50, unique=True)),
                ('sub_category_Code', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('sub_category_created_on', models.DateTimeField(auto_now=True)),
                ('sub_category_created_by', models.BigIntegerField()),
                ('sub_category_modified_on', models.DateTimeField(auto_now_add=True)),
                ('sub_category_modified_by', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterApiApp.IndustryCategoryModel')),
            ],
            options={
                'db_table': 'IndustrySubCategoryModel',
            },
        ),
        migrations.AddField(
            model_name='industrycategorymodel',
            name='maincore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterApiApp.IndustryMaincoreModel'),
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=50, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterApiApp.StateModel')),
            ],
            options={
                'db_table': 'CityModel',
            },
        ),
    ]
